<?php

/* components/footer.html */
class __TwigTemplate_6415f8501f7578be9ca6490610b84483246b1f4d627ddad4ac0ec0f002983d8f extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "<!DOCTYPE html>
<html><head>
<link rel=\"stylesheet\" href=\"../../../compiled/css/style.css\">

<script>
  function subst() {
    var vars={};
    var x=window.location.search.substring(1).split('&');
    for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
    var x=['frompage','topage','title', 'page','webpage','section','subsection','subsubsection'];
    for (var i in x) {
      var y = document.getElementsByClassName(x[i]);
      for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
    }
  }
  </script></head><body style=\"border:0; margin: 0;\" onload=\"subst()\">
  <table style=\"border-top: 1px solid #eee; width: 100%; margin-top: 10px;\">
    <tr>
      <td style=\"text-align: left; color: #666; font-size: 12px;\">Generated by Actuarial Systems Corporation</td>
      <td style=\"text-align: right; color: #666; font-size: 12px;\">
        Page <span class=\"page\"></span> of <span class=\"topage\"></span>
      </td>
    </tr>
  </table>
  </body></html>

";
    }

    public function getTemplateName()
    {
        return "components/footer.html";
    }

    public function getDebugInfo()
    {
        return array (  19 => 1,);
    }
}
